### ISSUE TITLE
App is damaged and cannot be opened

### ISSUE THREAD

**Issue by steakscience** [allenlsy/GoogleTasksMac#1]
Upon unzipping and opening the app, macOS gives an alert that the app is damaged. Compiling problem?

**Comment by allenlsy** [comment]
@SixFingeredAmish 

I think it's your mac os permission issue. Can you send a screenshot here?

And, try this command: `xattr -cr /Applications/Google\ Tasks.app`

**Comment by steakscience** [comment]
Resolved!
